export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const UPDATE_BOARDSTATE = 'UPDATE_BOARDSTATE';
export const TOGGLE_CURRENT_PLAYER = 'TOGGLE_CURRENT_PLAYER';
export const TOGGLE_CANPLAY = 'TOGGLE_CANPLAY';
export const RESET_BOARDSTATE = 'RESET_BOARDSTATE';
export const SET_WINNINGPLAYER = 'SET_WINNINGPLAYER';
export const SET_LASTPLAYED = 'SET_LASTPLAYED';
export const SET_CURRENT_PLAYER_NAME = 'SET_CURRENT_PLAYER_NAME';

export const SET_ROOM = 'SET_ROOM';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_USERS = 'SET_USERS';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_FIRSTPLAYER_NAME = 'SET_FIRSTPLAYER_NAME';
export const SET_SERVER_CANPLAY = 'SET_SERVER_CANPLAY';

export const GET_PLAYER_PROFILE = 'GET_PLAYER_PROFILE';
export const CREATE_PLAYER_PROFILE = 'CREATE_PLAYER_PROFILE';
export const UPDATE_PLAYER_PROFILE = 'UPDATE_PLAYER_PROFILE';
export const PROFILES_LOADING = 'PROFILES_LOADING';
